export default function AboutMe() {
    return (
        <div className="content">
            <img className="prof-img" src="../images/profile.png" alt="Profile Image" />
            <h1>About Me</h1>
            <p>I would post more content here but I am putting filler here to finish the assignment.</p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Beatae similique recusandae rerum harum esse ut? Rerum, dolorum sit mollitia quos reprehenderit eligendi temporibus, corporis cupiditate excepturi magnam laudantium hic. Et itaque quidem repudiandae commodi ratione, aperiam tempora aliquam neque id magnam pariatur voluptas vitae totam nihil nam cupiditate quas quam enim explicabo quos at eius architecto asperiores. Mollitia enim repellat a eum deleniti aliquam, rem maiores excepturi minus ab, quis esse velit molestias, possimus ullam. Non dolor eligendi, cupiditate modi voluptates ad placeat quisquam nam, quidem ab voluptatum recusandae assumenda consectetur! Odit ullam, nostrum quibusdam, hic laboriosam impedit explicabo facere quasi non earum quisquam, animi est! Labore eligendi eum ipsam ut aliquid. Nostrum voluptates vitae corrupti laboriosam optio impedit sapiente vero vel dicta eius similique doloribus dolores incidunt, odit sequi numquam. Quidem quasi, tenetur quia sed sit magnam deleniti porro, quod iure illo, recusandae optio corporis omnis culpa ut. Soluta recusandae repellat nesciunt adipisci ratione unde id aspernatur saepe incidunt quasi debitis exercitationem porro neque deleniti suscipit, nobis, assumenda officiis libero quae ipsa officia dicta tenetur! Dolorum exercitationem dolores perspiciatis mollitia, cupiditate fugiat? Ullam repellendus ipsa beatae vel asperiores omnis fugit tempora aliquid id consequuntur suscipit perferendis maiores molestiae repudiandae animi nihil neque deleniti voluptatem excepturi, alias assumenda voluptates voluptate odio. Qui facilis soluta velit? Accusantium aperiam, exercitationem ea vel labore fuga consequuntur expedita cumque quaerat. Sunt ducimus veritatis hic voluptatum autem, eum fugit maxime, ipsam esse quod quaerat possimus modi obcaecati ut nisi aut velit maiores! Doloribus ratione ab et ea perspiciatis dolore, laudantium nemo soluta minus? Totam alias officia dicta hic libero. Est asperiores et perferendis numquam ab molestias aperiam magnam vero, saepe tempora quia iusto delectus maxime dicta architecto quaerat, voluptate minus? Consequuntur error laboriosam, quos ullam exercitationem quisquam totam ipsum nulla? Laudantium vero, possimus cum iure nam ex quia laboriosam, ad incidunt id officia similique voluptatem, ducimus quo modi! Sint maxime ratione ut cumque aperiam voluptates! Ipsa laborum exercitationem, vel at distinctio voluptas nihil eaque tempora fugit, ipsum reiciendis molestias labore. Fugiat soluta sint possimus, expedita cumque porro perferendis eaque et labore laudantium dolores hic perspiciatis molestias consequuntur doloribus. Reprehenderit, vero, voluptas numquam possimus non velit quae autem doloribus inventore cumque dolores consequatur voluptate molestiae enim.</p>
        </div>
    )

}
